### ISSUE TITLE
Possible typo in `final_2016.R`?

### ISSUE THREAD

**Issue by tcbegley** [TheEconomist/us-potus-model#9]
Hello,

Is the use of `poll_mode_*` variables for the `poll_pop_*` parameters [here](https://github.com/TheEconomist/us-potus-model/blob/bd1536b628eb1f97f2a8c303a0c1b42e2c04ff02/scripts/model/final_2016.R#L390-L391) intentional or is it a typo?

EDIT - On a related note, it looks like there is a typo (or at least redundancy) [in the definition of `poll_pop_state`](https://github.com/TheEconomist/us-potus-model/blob/bd1536b628eb1f97f2a8c303a0c1b42e2c04ff02/scripts/model/final_2016.R#) which uses `index_p` rather than `index_pop` and hence is identical to `poll_state`, [defined a few lines earlier](https://github.com/TheEconomist/us-potus-model/blob/bd1536b628eb1f97f2a8c303a0c1b42e2c04ff02/scripts/model/final_2016.R#L346).

**Comment by elliottmorris** [comment]
That is indeed a rather egregious typo! It has been fixed, and we'll push a commit with the updated model diagnostics soon. 

The good news is that the `index_p` and `index_pop` confusion wasn't entering the model because of the `poll_mode_*` and `poll_pop_*` confusion a few lines lower. (And if it did, the model would have just broke). So thing are wrong, but this won't change much. 

Thanks again!
